### ISSUE TITLE
Any tips on improving performance on Mac? Extremely slow

### ISSUE THREAD

**Issue by briantully** [DrupalStand/drupal-dev-docker#52]
Hey there. I was wondering if anyone has tried using this on a Mac with any success. I've been trying for the past week but had to give up due to how slow/unresponsive it was. I've even tried giving Docker Desktop all my CPU and Memory to no avail. A simple drush command can take over 5 minutes :(

Any help or advice would be greatly appreciated :)

**Comment by Cromian** [comment]
Hi @briantully I know the feeling quite well. Perhaps this may help you https://github.com/DrupalStand/mac-stand. Since docker for Mac runs on LinuxKit, this spins up Docker within a Linux VirtualBox VM with an NFS mount. I use this locally and found it dramatically improves performance when it comes to large scale Drupal projects. The only downside is that you will need to run the commands within the VM but as this uses Vagrant you would simply just run `vagrant ssh` and then cd into `var/www/html`. Let me know if you have any questions.

**Comment by briantully** [comment]
Thanks for the response, @Cromian . In looking through mac-stand, I didn't see anything in the Vagrantfile or bootstrap.sh that was Drupal-specific. Does Drupal (and drush, drupal console, memcached, etc) need to be added manually or does mac-stand somehow integrate with drupal-dev-docker to get all the nice tools? 

Otherwise, if it's leveraging Vagrant for NFS, why would I choose mac-stand over something like DrupalVM?

Sorry for all the questions! Thanks again :)

**Comment by Cromian** [comment]
No problem. The latter. In short this is just a bare-bone alternative to docker for Mac desktop. Once you spin this up just clone drupal-dev-docker into the html directory, ssh into the box, and run `make-init`. Drupal-dev-docker takes care of the rest. This just provides a faster vehicle to run it. Hope that helps.

**Comment by briantully** [comment]
@Cromian that’s great news! Thank you so much for the help. You literally saved me from pulling all my hair out 😜 I owe you several beers🍺🍺🍺
